---
# Already exists on all servers as there is filebeat already configured 

- name: Add rpm key for elastic.co
  rpm_key:
    key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: "present"

- name: Create filebeat repository
  yum_repository:
    name: beats
    description: RPM Metricbeat repo
    baseurl: "https://artifacts.elastic.co/packages/7.x/yum"
    enabled: yes
    gpgcheck: yes
    gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

- name: Install metricbeat - RedHat
  yum:
    name: "{{ metricbeat_version }}"
    state: "present"

- name: Start and enable metricbeat - RedHat
  service:
    name: metricbeat
    state: started
    enabled: true
